In [308]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

In [309]:
df = pd.read_csv('Bengaluru_House_Data.csv')
df.head(10)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.00
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4.0,NaN,600.00
8,Super built-up Area,Ready To Move,Marathahalli,3 BHK,NaN,1310,3.0,1.0,63.25
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020,6.0,NaN,370.00

In [310]:
print("Size:",df.shape)

Size: (13320, 9)

In [311]:
# print null values count
print("Null values count:",f"\n{df.isnull().sum()}")

Null values count:
area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [312]:
def list_diff_values_format(column):
    # 1. Get ALL unique values from the column
    all_unique_values = df[column].dropna().unique()
    unique_formats = {}
    for item in all_unique_values:
        item_str = str(item).strip() # remove leading/trailing whitespaces
        # 2. Categorize the format
        if '-' in item_str:
            format_type = 'Range'
        else:
            # Extract only alphabetic characters to find the unit
            unit = re.sub(r'[^a-zA-Z]', '', item_str)

            if unit == '': # if no unit, it's a number
                format_type = 'Number'
            else:
                format_type = unit # e.g., 'SqMeter', 'Acres'

        # 3. Store the first example of each format found
        if format_type not in unique_formats:
            unique_formats[format_type] = item_str

    # 4. Display the results
    print(f"{'FORMAT TYPE':<15} | {'EXAMPLE'}")
    print("-" * 35)
    for fmt, example in unique_formats.items():
        print(f"{fmt:<15} | {example}")

In [313]:
# print only the rows which have null values in location column
df[df['location'].isnull()]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
568,Super built-up Area,Ready To Move,NaN,3 BHK,Grare S,1600,3.0,2.0,86.0

In [314]:
# drop the null values in location column due to the fact that location is a 
# very important feature and we cannot fill it with any other value
df.dropna(subset=['location'], inplace=True)

In [315]:
# print only the rows which have null values in size column
df[df['size'].isnull()]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
579,Plot Area,Immediate Possession,Sarjapur Road,NaN,Asiss B,1200 - 2400,NaN,NaN,34.185
1775,Plot Area,Immediate Possession,IVC Road,NaN,Orana N,2000 - 5634,NaN,NaN,124.000
2264,Plot Area,Immediate Possession,Banashankari,NaN,NaN,2400,NaN,NaN,460.000
2809,Plot Area,Immediate Possession,Sarjapur Road,NaN,AsdiaAr,1200 - 2400,NaN,NaN,28.785
2862,Plot Area,Immediate Possession,Devanahalli,NaN,Ajleyor,1500 - 2400,NaN,NaN,46.800
5333,Plot Area,Immediate Possession,Devanahalli,NaN,Emngs S,2100 - 5405,NaN,NaN,177.115
6423,Plot Area,Immediate Possession,Whitefield,NaN,SRniaGa,2324,NaN,NaN,26.730
6636,Plot Area,Immediate Possession,Jigani,NaN,S2enste,1500,NaN,NaN,25.490
6719,Plot Area,Immediate Possession,Hoskote,NaN,SJowsn,800 - 2660,NaN,NaN,28.545
7680,Plot Area,Immediate Possession,Kasavanhalli,NaN,NaN,5000,NaN,NaN,400.000
8306,Plot Area,Immediate Possession,Anekal,NaN,Vaensnd,1453,NaN,NaN,16.500
8565,Plot Area,Immediate Possession,Carmelaram,NaN,Ocezes,2000,NaN,NaN,120.000
8703,Plot Area,Immediate Possession,Mysore Road,NaN,Naoden,1200 - 2400,NaN,NaN,42.300
10634,Plot Area,Immediate Possession,Rajankunte,NaN,NaN,1575,NaN,NaN,31.110
11019,Plot Area,Immediate Possession,Yelahanka,NaN,Saaveha,1200 - 1800,NaN,NaN,12.750
11569,Plot Area,Immediate Possession,Hosur Road,NaN,AVeldun,1350,NaN,NaN,8.440

In [316]:
# drop the null values in size column due to the fact that size is a 
# very important feature and we cannot fill it with any other value
df.dropna(subset=['size'], inplace=True)

In [317]:
# print the row which does not have a number in size column
df[df['size'].str.extract('(\d+)')[0].isnull()]

Empty DataFrame
Columns: [area_type, availability, location, size, society, total_sqft, bath, balcony, price]
Index: []

In [318]:
# print only the rows which have null values in society column
df[df['society'].isnull()]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
8,Super built-up Area,Ready To Move,Marathahalli,3 BHK,NaN,1310,3.0,1.0,63.25
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020,6.0,NaN,370.00
10,Super built-up Area,18-Feb,Whitefield,3 BHK,NaN,1800,2.0,2.0,70.00
...,...,...,...,...,...,...,...,...,...
13310,Super built-up Area,Ready To Move,Rachenahalli,2 BHK,NaN,1050,2.0,2.0,52.71
13311,Plot Area,Ready To Move,Ramamurthy Nagar,7 Bedroom,NaN,1500,9.0,2.0,250.00
13312,Super built-up Area,Ready To Move,Bellandur,2 BHK,NaN,1262,2.0,2.0,47.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [319]:
df.fillna({'society': 'No Society'}, inplace=True)

In [320]:
df[df['bath'].isnull()]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
56,Built-up Area,20-Feb,Devanahalli,4 Bedroom,BrereAt,3010 - 3410,NaN,NaN,192.000
81,Built-up Area,18-Oct,Hennur Road,4 Bedroom,Gollela,2957 - 3450,NaN,NaN,224.500
224,Super built-up Area,19-Dec,Devanahalli,3 BHK,Jurdsig,1520 - 1740,NaN,NaN,74.820
344,Super built-up Area,21-Dec,Kanakpura Road,1 BHK,PrarePa,525,NaN,NaN,21.530
669,Super built-up Area,18-Dec,JP Nagar,5 BHK,Pehtsa,4400 - 6640,NaN,NaN,375.000
702,Super built-up Area,18-Dec,JP Nagar,5 BHK,Pehtsa,4400 - 6800,NaN,NaN,548.500
801,Super built-up Area,18-Dec,JP Nagar,4 BHK,Pehtsa,4000 - 5249,NaN,NaN,453.000
941,Super built-up Area,Ready To Move,Whitefield,4 Bedroom,PrOakSi,3606 - 5091,NaN,NaN,304.000
1264,Built-up Area,18-May,Hennur,3 Bedroom,Asoilul,2264,NaN,NaN,155.000
1267,Super built-up Area,18-Jun,Yelahanka,3 BHK,Shalkri,1440 - 1884,NaN,NaN,67.980
1686,Super built-up Area,21-Dec,Whitefield,1 BHK,SudenEd,660 - 670,NaN,NaN,28.585
1724,Super built-up Area,Ready To Move,Thanisandra,1 BHK,Bhmesy,620 - 933,NaN,NaN,48.145
1765,Super built-up Area,19-Dec,Binny Pete,4 BHK,Shestlo,2695 - 2940,NaN,NaN,204.000
1852,Super built-up Area,19-Jun,Yelahanka,4 BHK,Vaaram,3450 - 3472,NaN,NaN,173.000
2500,Super built-up Area,22-May,Jakkur,4 BHK,SoineC,2249.81 - 4112.19,NaN,NaN,260.500
2563,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,PhestOn,3436 - 3643,NaN,NaN,424.500
2944,Super built-up Area,18-Dec,Kudlu Gate,3 BHK,Sanzaat,1564 - 1850,NaN,NaN,99.745
2998,Super built-up Area,19-May,Sarjapur Road,3 BHK,Klark L,1446 - 1506,NaN,NaN,98.940
3370,Super built-up Area,Ready To Move,Kanakpura Road,3 BHK,Wiowsri,1430 - 1630,NaN,NaN,66.400
3544,Super built-up Area,19-Mar,Hennur Road,3 BHK,Puachal,1482 - 1846,NaN,NaN,93.865
3598,Super built-up Area,18-Jun,Haralur Road,4 BHK,SNnia E,2805 - 3565,NaN,NaN,175.000
3862,Super built-up Area,Ready To Move,Jigani,4 Bedroom,Prllasw,3293 - 5314,NaN,NaN,226.000
4210,Super built-up Area,Ready To Move,Malleshwaram,3 BHK,Sariaat,2215 - 2475,NaN,NaN,293.000
4346,Super built-up Area,18-Dec,Whitefield,3 BHK,Prtates,1650 - 2538,NaN,NaN,113.190
4843,Super built-up Area,18-Mar,Bhoganhalli,4 BHK,Rosha I,1974 - 2171,NaN,NaN,111.000
4894,Super built-up Area,Ready To Move,Bommanahalli,3 BHK,SNeur G,1360 - 1890,NaN,NaN,87.720
4995,Super built-up Area,18-Mar,Hebbal,3 BHK,SNontle,2466 - 2856,NaN,NaN,226.500
5464,Super built-up Area,18-Sep,KR Puram,3 BHK,MCnexva,1310 - 1615,NaN,NaN,62.810
5498,Built-up Area,Ready To Move,Chandapura,4 Bedroom,MRowsea,1782 - 2000,NaN,NaN,66.165
5747,Super built-up Area,18-Apr,Kanakpura Road,1 BHK,PrarePa,525,NaN,NaN,27.000
5918,Super built-up Area,Ready To Move,Sarjapur Road,4 BHK,Klark L,4260 - 4408,NaN,NaN,338.000
6256,Built-up Area,Ready To Move,Electronic City Phase II,4 Bedroom,Shrds O,3500 - 3600,NaN,NaN,167.500
6343,Super built-up Area,18-May,KR Puram,3 BHK,TGasyhu,1482 - 1684,NaN,NaN,70.445
6481,Super built-up Area,18-Jun,Chandapura,3 BHK,SuVue S,1100 - 1225,NaN,NaN,30.215
6778,Super built-up Area,Ready To Move,Old Madras Road,4 BHK,Saciatt,4050 - 4075,NaN,NaN,341.000
6873,Super built-up Area,18-Mar,JP Nagar,3 BHK,Shestut,1750 - 2640,NaN,NaN,152.000
6971,Super built-up Area,18-Dec,Whitefield,3 BHK,BSlasin,1390 - 1600,NaN,NaN,61.280
7398,Super built-up Area,18-Dec,JP Nagar,3 BHK,Pehtsa,3103 - 3890,NaN,NaN,237.500
7623,Super built-up Area,Ready To Move,Electronics City Phase 1,3 BHK,Shitt S,1450 - 1595,NaN,NaN,60.750
7921,Super built-up Area,18-Mar,Sarjapur Road,3 BHK,PualeSk,1618 - 1929,NaN,NaN,85.125
8020,Super built-up Area,22-May,Jakkur,4 BHK,SoineC,2249.81 - 4112.19,NaN,NaN,229.000
8056,Super built-up Area,Ready To Move,Jakkur,3 BHK,BrdgeNo,1610 - 1880,NaN,NaN,98.485
8275,Super built-up Area,21-Dec,Kanakpura Road,1 BHK,PrarePa,525,NaN,NaN,29.250
8289,Super built-up Area,18-Apr,Kanakpura Road,2 BHK,PrarePa,700 - 900,NaN,NaN,41.145
8472,Super built-up Area,18-Dec,Sarjapur,4 BHK,Kinuerg,1925 - 2680,NaN,NaN,80.590
8783,Super built-up Area,18-Dec,Whitefield,3 BHK,BSlasin,1390 - 1600,NaN,NaN,60.550
9129,Super built-up Area,18-May,Mysore Road,3 BHK,Brama P,1410 - 1710,NaN,NaN,83.300
9437,Built-up Area,18-May,Hennur,4 Bedroom,Asoilul,2557,NaN,NaN,170.000
9699,Super built-up Area,18-Jul,Bannerghatta,4 BHK,Mamespa,1791 - 4000,NaN,NaN,246.000
10330,Super built-up Area,Ready To Move,Kanakpura Road,3 BHK,Wiowsri,1430 - 1630,NaN,NaN,70.990
10553,Built-up Area,Ready To Move,Sarjapur Road,4 Bedroom,AztheBr,3418,NaN,NaN,222.000
10726,Super built-up Area,18-Mar,Sarjapur Road,3 BHK,PualeSk,1618 - 1929,NaN,NaN,102.920
11297,Super built-up Area,18-Dec,Hennur,4 BHK,Exitym,3484 - 3550,NaN,NaN,161.500
11496,Super built-up Area,21-Dec,Kanakpura Road,1 BHK,PrarePa,525,NaN,NaN,27.000
12768,Built-up Area,18-Mar,Bettahalsoor,5 Bedroom,Toainnt,3210,NaN,NaN,353.000
12861,Super built-up Area,21-Dec,KR Puram,4 BHK,Moquach,2204 - 2362,NaN,NaN,121.000
13240,Super built-up Area,Ready To Move,Devanahalli,1 BHK,Pardsri,1020 - 1130,NaN,NaN,52.570

In [321]:
# extract the number of bedrooms from the size column and create a new column called bhk
df['bhk'] = df['size'].str.extract('(\d+)').astype(int)

# smart imputation for the bath column using the median value of the bath column for each bhk
df['bath'] = df['bath'].fillna(
    df.groupby('bhk')['bath'].transform('median')
)

# round the bath column to the nearest integer and convert it to int type
df['bath'] = df['bath'].round().astype(int)

In [322]:
df['bath'].value_counts()

bath
2     6909
3     3309
4     1248
1      795
5      527
6      273
7      102
8       64
9       43
10      13
12       7
13       3
11       3
16       2
27       1
40       1
15       1
14       1
18       1
Name: count, dtype: int64

In [323]:
df[df['balcony'].isnull()]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4,NaN,204.00,4
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4,NaN,600.00,4
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,No Society,1020,6,NaN,370.00,6
34,Built-up Area,Ready To Move,Kasturi Nagar,3 BHK,Kantsce,1925,3,NaN,125.00,3
40,Built-up Area,Ready To Move,Murugeshpalya,2 BHK,Gentson,1296,2,NaN,81.00,2
...,...,...,...,...,...,...,...,...,...,...
13277,Plot Area,Ready To Move,Kundalahalli Colony,7 Bedroom,No Society,1400,7,NaN,218.00,7
13279,Plot Area,Ready To Move,Vishwanatha Nagenahalli,6 Bedroom,No Society,1200,5,NaN,130.00,6
13306,Plot Area,Ready To Move,Rajarajeshwari Nagara,4 Bedroom,No Society,1200,5,NaN,325.00,4
13309,Super built-up Area,Ready To Move,Yeshwanthpur,3 BHK,IBityin,1675,3,NaN,92.13,3
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,No Society,3600,5,NaN,400.00,4

In [324]:
# fill missing balcony as no balcony
df['balcony'] = df['balcony'].fillna(0)

In [325]:
df.isnull().sum()

area_type       0
availability    0
location        0
size            0
society         0
total_sqft      0
bath            0
balcony         0
price           0
bhk             0
dtype: int64

In [326]:
list_diff_values_format('total_sqft')

FORMAT TYPE     | EXAMPLE
-----------------------------------
Number          | 1056
Range           | 2100 - 2850
SqMeter         | 34.46Sq. Meter
Perch           | 4125Perch
SqYards         | 1100Sq. Yards
Acres           | 5.31Acres
Cents           | 3Cents
Guntha          | 24Guntha
Grounds         | 1Grounds

In [327]:
def convert_sqft_to_num(x):
    if isinstance(x, float):
        return x
    x = str(x).strip()
    # ---------- RANGE ----------
    if '-' in x:
        tokens = x.split('-')
        if len(tokens) == 2:
            try:
                return (float(tokens[0]) + float(tokens[1])) / 2
            except:
                return np.nan

    # ---------- NORMAL NUMBER ----------
    try:
        return float(x)
    except:
        pass

    # ---------- UNIT CONVERSIONS ----------
    unit_mapping = {
        'Sq. Meter': 10.7639,
        'Sq. Yards': 9,
        'Perch': 272.25,
        'Acres': 43560,
        'Cents': 435.6,
        'Guntha': 1089,
        'Grounds': 2400
    }
    for unit in unit_mapping:
        if unit in x:
            try:
                value = float(x.replace(unit, '').strip())
                return value * unit_mapping[unit]
            except:
                return np.nan
    return np.nan

In [328]:
# Convert all values into numeric
df['total_sqft'] = df['total_sqft'].apply(convert_sqft_to_num)

In [329]:
# Create useful columns
df['total_price'] = df['price'] * 100000
df['price_per_sqft'] = (df['total_price'] / df['total_sqft']).round(2)

In [330]:
# now remove 'bhk' and 'price' column that are created during cleaning process
df.drop('bhk', axis=1, inplace=True)
df.drop('price', axis=1, inplace=True)

In [331]:
# fix datatypes
cols = ['area_type', 'availability', 'location', 'size', 'society']
df[cols] = df[cols].astype(str).apply(lambda x: x.str.lower())
df['bath']=df['bath'].astype(int)
df['balcony']=df['balcony'].astype(int)
df['total_price']=df['total_price'].astype(int)

# reset the index of the dataframe
df.reset_index(inplace=True, drop=True)

In [338]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,total_price,price_per_sqft
0,super built-up area,19-dec,electronic city phase ii,2 bhk,coomee,1056.0,2,1,3907000,3699.81
1,plot area,ready to move,chikka tirupathi,4 bedroom,theanmp,2600.0,5,3,12000000,4615.38
2,built-up area,ready to move,uttarahalli,3 bhk,no society,1440.0,2,3,6200000,4305.56
3,super built-up area,ready to move,lingadheeranahalli,3 bhk,soiewre,1521.0,3,1,9500000,6245.89
4,super built-up area,ready to move,kothanur,2 bhk,no society,1200.0,2,1,5100000,4250.00
...,...,...,...,...,...,...,...,...,...,...
13298,built-up area,ready to move,whitefield,5 bedroom,arsiaex,3453.0,4,0,23100000,6689.83
13299,super built-up area,ready to move,richards town,4 bhk,no society,3600.0,5,0,40000000,11111.11
13300,built-up area,ready to move,raja rajeshwari nagar,2 bhk,mahla t,1141.0,2,1,6000000,5258.55
13301,super built-up area,18-jun,padmanabhanagar,4 bhk,sollycl,4689.0,4,1,48800000,10407.34
13302,super built-up area,ready to move,doddathoguru,1 bhk,no society,550.0,1,1,1700000,3090.91

In [333]:
df.isnull().sum()

area_type         0
availability      0
location          0
size              0
society           0
total_sqft        0
bath              0
balcony           0
total_price       0
price_per_sqft    0
dtype: int64

In [334]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13303 entries, 0 to 13302
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   area_type       13303 non-null  object
 1   availability    13303 non-null  object
 2   location        13303 non-null  object
 3   size            13303 non-null  object
 4   society         13303 non-null  object
 5   total_sqft      13303 non-null  float64
 6   bath            13303 non-null  int32
 7   balcony         13303 non-null  int32
 8   total_price     13303 non-null  int32
 9   price_per_sqft  13303 non-null  float64
dtypes: float64(2), int32(3), object(5)
memory usage: 883.5+ KB

In [335]:
# Save the cleaned dataset to a CSV file
df.to_csv("Cleaned_Bengaluru_House_Data.csv", index=False)

print("Cleaned Dataset is saved as Cleaned_Bengaluru_House_Data.csv")

Cleaned Dataset is saved as Cleaned_Bengaluru_House_Data.csv